# if you dont specify locked attribute, the default value will be true
# which means the particular config will be locked
- name: INSTALLATION_NAME
  value: 'Wozechat'
- name: LOGO_THUMBNAIL
  value: 'https://s.woze.app/logo_thumbnail.svg'
- name: LOGO
  value: 'https://s.woze.app/logo.svg'
- name: BRAND_URL
  value: 'https://woze.app'
- name: WIDGET_BRAND_URL
  value: 'https://woze.app'
- name: BRAND_NAME
  value: 'Wozechat'
- name: TERMS_URL
  value: 'https://woze.app/terms-of-service'
- name: PRIVACY_URL
  value: 'https://woze.app/privacy-policy'
- name: DISPLAY_MANIFEST
  value: true
- name: MAILER_INBOUND_EMAIL_DOMAIN
  value:
  locked: false
- name: MAILER_SUPPORT_EMAIL
  value:
  locked: false
- name: CREATE_NEW_ACCOUNT_FROM_DASHBOARD
  value: false
  locked: false
- name: INSTALLATION_EVENTS_WEBHOOK_URL
  value:
  locked: false
- name: CHATWOOT_INBOX_TOKEN
  value:
  locked: false
- name: CHATWOOT_INBOX_HMAC_KEY
  value:
  locked: false
- name: API_CHANNEL_NAME
  value:
- name: API_CHANNEL_THUMBNAIL
  value:
